name: CI/CD for Odoo Docker Image to ACR

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (Development/Production)'
        required: true
        default: 'development'
      odoo_version:
        description: 'Odoo Version'
        required: true
        default: '18.0'

jobs:
  build-and-push:
    name: Build and Push Odoo Docker Image to ACR
    runs-on: ubuntu-latest

    steps:
      # Checkout Odoo Docker repository
      - name: Checkout Odoo Repository
        uses: actions/checkout@v3
        with:
          repository: trplgit/odoo-docker
          token: ${{ secrets.GH_TOKEN }}
          path: odoo-docker

      # Set up Docker buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.ACR_NAME }}.azurecr.io
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and Push Odoo Docker Image (odoo-18:latest)
      - name: Build and Push Odoo Docker Image
        run: |
          docker build -f ./odoo-docker/${{ inputs.odoo_version }}/Dockerfile -t ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.environment }}/odoo-18:latest ./odoo-docker/${{ inputs.odoo_version }}
          docker push ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.environment }}/odoo-18:latest
