name: CI/CD for Odoo Docker

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      environment:
        description: 'Environment to deploy (Development/Production)'
        required: true
        default: 'development'
      odoo_version:
        description: 'Odoo Version'
        required: true
        default: '18.0'

jobs:
  build-and-push:
    name: Build and Push Docker Image for Odoo
    runs-on: ubuntu-latest

    steps:
      # Checkout Odoo Docker repository
      - name: Checkout Odoo Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Verify Odoo Docker repository directory structure
      - name: List Odoo Docker repository structure
        run: |
          echo "Listing the directory structure of the Odoo Docker repository"
          ls -R ./  # List all files and directories recursively after checkout

      # Check if 18.0 folder exists in Odoo Docker repository
      - name: Check 18.0 directory inside Odoo Docker repository
        run: |
          echo "Checking contents inside the 18.0 folder in Odoo Docker repository"
          ls -R ./18.0  # List contents inside the 18.0 folder

      # Build Docker image for Odoo from 18.0 directory
      - name: Build Docker image for Odoo from 18.0 directory
        run: |
          # Ensure the 18.0 directory exists and the Dockerfile is accessible
          ls -R ./18.0  # Check if the 18.0 directory exists
          
          # Build Docker image for Odoo from the 18.0 directory
          docker build -f ./18.0/Dockerfile -t my-odoo-image ./  # Build the Docker image with the right context (root directory)

          # Push Docker image to Azure Container Registry
          docker push ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.environment }}/odoo-docker:${{ inputs.odoo_version }}
