jobs:
  build-and-push:
    name: Build and Push Docker Image for Odoo
    runs-on: ubuntu-latest

    steps:
      # Checkout Odoo Docker repository
      - name: Checkout Odoo Repository
        uses: actions/checkout@v3jobs:
  build-and-push:
    name: Build and Push Docker Image for Odoo
    runs-on: ubuntu-latest

    steps:
      # Checkout Odoo Docker repository
      - name: Checkout Odoo Repository
        uses: actions/checkout@v3
        with:
          repository: trplgit/odoo-docker
          token: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.ACR_NAME }}.azurecr.io
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Verify Odoo Docker repository directory structure
      - name: List Odoo Docker repository structure
        run: |
          echo "Listing the directory structure of the Odoo Docker repository"
          ls -R ./  # List all files and directories recursively after checkout

      # Check if 18.0 folder exists in Odoo Docker repository
      - name: Check 18.0 directory inside Odoo Docker repository
        run: |
          echo "Checking contents inside the 18.0 folder in Odoo Docker repository"
          ls -R ./18.0  # List contents inside the 18.0 folder

      # Build and Push Odoo Docker Image
      - name: Build and Push Odoo Docker Image
        run: |
          # Ensure the Docker context is set to the 18.0 directory
          docker build -f ./18.0/Dockerfile -t my-odoo-image ./18.0  # Set context to the 18.0 folder
          
          # Push Docker image to Azure Container Registry
          docker push ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.environment }}/odoo-docker:${{ inputs.odoo_version }}

        with:
          repository: trplgit/odoo-docker
          token: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.ACR_NAME }}.azurecr.io
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Verify Odoo Docker repository directory structure
      - name: List Odoo Docker repository structure
        run: |
          echo "Listing the directory structure of the Odoo Docker repository"
          ls -R ./  # List all files and directories recursively after checkout

      # Check if 18.0 folder exists in Odoo Docker repository
      - name: Check 18.0 directory inside Odoo Docker repository
        run: |
          echo "Checking contents inside the 18.0 folder in Odoo Docker repository"
          ls -R ./18.0  # List contents inside the 18.0 folder

      # Build and Push Odoo Docker Image
      - name: Build and Push Odoo Docker Image
        run: |
          # Ensure the Docker context is set to the 18.0 directory
          docker build -f ./18.0/Dockerfile -t my-odoo-image ./18.0  # Set context to the 18.0 folder
          
          # Push Docker image to Azure Container Registry
          docker push ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.environment }}/odoo-docker:${{ inputs.odoo_version }}
