name: Check Docker Build for Odoo

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      environment:
        description: 'Environment to deploy (Development/Production)'
        required: true
        default: 'development'
      odoo_version:
        description: 'Odoo Version'
        required: true
        default: '18.0'

jobs:
  build:
    name: Build Docker Image for Odoo
    runs-on: ubuntu-latest

    steps:
      # Checkout Odoo Docker repository
      - name: Checkout Odoo Repository
        uses: actions/checkout@v3
        with:
          repository: trplgit/odoo-docker
          token: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      # Verify Odoo Docker repository directory structure
      - name: List Odoo Docker repository structure
        run: |
          echo "Listing the directory structure of the Odoo Docker repository"
          ls -R ./  # List all files and directories recursively after checkout

      # Check if 18.0 folder exists in Odoo Docker repository
      - name: Check 18.0 directory inside Odoo Docker repository
        run: |
          echo "Checking contents inside the 18.0 folder in Odoo Docker repository"
          ls -R ./18.0  # List contents inside the 18.0 folder

      # Build Docker image for Odoo
      - name: Build Docker image
        run: |
          echo "Building Docker image from ./18.0/Dockerfile"
          docker build -f ./18.0/Dockerfile -t my-odoo-image .

      # Verify Docker image is built
      - name: Verify Docker image
        run: |
          echo "Listing Docker images"
          docker images | grep my-odoo-image
