name: CI/CD for Odoo and PostgreSQL Docker

on:
  workflow_dispatch: # Manual trigger
    inputs:
      environment:
        description: 'Environment to deploy (Development/Production)'
        required: true
        default: 'development'
      postgres_version:
        description: 'PostgreSQL Version'
        required: true
        default: '17'
      odoo_version:
        description: 'Odoo Version'
        required: true
        default: '18.0'

jobs:
  build-and-push:
    name: Build and Push Docker Images for Odoo and PostgreSQL
    runs-on: ubuntu-latest

    steps:
      # Checkout Odoo Docker Repository
      - name: Checkout Odoo Docker Repository
        uses: actions/checkout@v3
        with:
          repository: trplgit/odoo-docker
          token: ${{ secrets.GITHUB_TOKEN }}

      # Checkout PostgreSQL Docker Repository
      - name: Checkout PostgreSQL Repository
        uses: actions/checkout@v3
        with:
          repository: trplgit/postgres
          token: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.ACR_NAME }}.azurecr.io
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # List Odoo repository structure to check for version directory
      - name: List Odoo Docker repository structure
        run: |
          echo "Listing Odoo Docker repository structure"
          ls -R ./  # List all files and directories recursively

      # Check if 18.0 folder exists in Odoo Docker repository
      - name: Check Odoo 18.0 directory
        run: |
          echo "Checking contents inside the 18.0 folder in Odoo Docker repository"
          ls -R ./18.0 || echo "Directory 18.0 does not exist"

      # Build and Push Odoo Docker Image
      - name: Build and Push Odoo Docker Image
        run: |
          docker build -f ./18.0/Dockerfile -t ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.environment }}/odoo-docker:${{ inputs.odoo_version }} ./18.0
          docker push ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.environment }}/odoo-docker:${{ inputs.odoo_version }}

      # List PostgreSQL repository structure to check for version directory
      - name: List PostgreSQL Docker repository structure
        run: |
          echo "Listing PostgreSQL Docker repository structure"
          ls -R ./  # List all files and directories recursively

      # Check if PostgreSQL version folder exists
      - name: Check PostgreSQL version directory
        run: |
          echo "Checking contents inside the version folder for PostgreSQL"
          ls -R ./${{ inputs.postgres_version }} || echo "Directory for PostgreSQL version does not exist"

      # Build and Push PostgreSQL Docker Image
      - name: Build and Push PostgreSQL Docker Image
        run: |
          docker build -f ./${{ inputs.postgres_version }}/alpine3.21/Dockerfile -t ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.environment }}/postgres:${{ inputs.postgres_version }} ./${{ inputs.postgres_version }}
          docker push ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.environment }}/postgres:${{ inputs.postgres_version }}

  deploy:
    name: Deploy to Linux VM
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Install OpenVPN
      - name: Install OpenVPN
        run: sudo apt-get install -y openvpn

      # Prepare VPN files
      - name: Prepare VPN Files
        run: |
          echo "${{ secrets.VPN_PKCS12_FILE }}" | base64 -d > TRPL-FW-TCP-1194-ci-cd-automation.p12
          echo "${{ secrets.VPN_TLS_KEY_FILE }}" | base64 -d > TRPL-FW-TCP-1194-ci-cd-automation-tls.key

      # Connect to VPN
      - name: Connect to VPN
        run: |
          echo "${{ secrets.VPN_CONFIG_FILE }}" > vpn-config.ovpn
          echo -e "${{ vars.VPN_USERNAME }}\n${{ secrets.VPN_PASSWORD }}" > vpn-credentials.txt
          sudo openvpn --config vpn-config.ovpn --auth-user-pass vpn-credentials.txt --daemon

      # Wait for VPN connection
      - name: Wait for VPN Connection
        run: sleep 15

      # Verify VPN connection
      - name: Verify VPN Connection
        run: |
          ifconfig | grep tun || (echo "VPN connection failed" && exit 1)

      # Deploy PostgreSQL Docker container to VM
      - name: Deploy PostgreSQL Docker Container to VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ vars.LINUX_VM_HOST_DEVELOPMENT }}
          username: ${{ vars.LINUX_VM_USERNAME_DEVELOPMENT }}
          password: ${{ secrets.LINUX_VM_PASSWORD_DEVELOPMENT }}
          port: 22
          script: |
            echo "${{ secrets.LINUX_VM_PASSWORD_DEVELOPMENT }}" | sudo -S docker login ${{ vars.ACR_NAME }}.azurecr.io -u ${{ vars.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
            echo "${{ secrets.LINUX_VM_PASSWORD_DEVELOPMENT }}" | sudo -S docker pull ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.environment }}/postgres:${{ inputs.postgres_version }}
            echo "${{ secrets.LINUX_VM_PASSWORD_DEVELOPMENT }}" | sudo -S docker stop postgres-container || true
            echo "${{ secrets.LINUX_VM_PASSWORD_DEVELOPMENT }}" | sudo -S docker rm postgres-container || true
            echo "${{ secrets.LINUX_VM_PASSWORD_DEVELOPMENT }}" | sudo -S docker run -d --restart always --name postgres-container --network=odoo-postgres-network -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -p 5432:5432 ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.environment }}/postgres:${{ inputs.postgres_version }}

      # Deploy Odoo Docker container to VM
      - name: Deploy Odoo Docker Container to VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ vars.LINUX_VM_HOST_DEVELOPMENT }}
          username: ${{ vars.LINUX_VM_USERNAME_DEVELOPMENT }}
          password: ${{ secrets.LINUX_VM_PASSWORD_DEVELOPMENT }}
          port: 22
          script: |
            echo "${{ secrets.LINUX_VM_PASSWORD_DEVELOPMENT }}" | sudo -S docker login ${{ vars.ACR_NAME }}.azurecr.io -u ${{ vars.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
            echo "${{ secrets.LINUX_VM_PASSWORD_DEVELOPMENT }}" | sudo -S docker pull ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.environment }}/odoo-docker:${{ inputs.odoo_version }}
            echo "${{ secrets.LINUX_VM_PASSWORD_DEVELOPMENT }}" | sudo -S docker stop odoo-container || true
            echo "${{ secrets.LINUX_VM_PASSWORD_DEVELOPMENT }}" | sudo -S docker rm odoo-container || true
            echo "${{ secrets.LINUX_VM_PASSWORD_DEVELOPMENT }}" | sudo -S docker run -d --restart always --name odoo-container --network=odoo-postgres-network -p 8069:8069 ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.environment }}/odoo-docker:${{ inputs.odoo_version }}

      # Cleanup VPN credentials
      - name: Cleanup VPN Credentials
        run: |
          rm -f vpn-config.ovpn vpn-credentials.txt
